# Generated by Django 3.2.1 on 2023-06-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='role_id',
            field=models.PositiveIntegerField(choices=[(1, 'User'), (2, 'Job Seeker')], default=1),
            preserve_default=False,
        ),
    ]
