# Generated by Django 3.2.1 on 2023-06-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobseeker_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='role_id',
            field=models.PositiveIntegerField(choices=[(1, 'User'), (2, 'Job Seeker')], default=1),
        ),
    ]
