# Generated by Django 3.2.1 on 2023-06-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobseeker_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=122, null=True)),
                ('subject', models.CharField(max_length=122, unique=True)),
                ('message', models.CharField(max_length=122)),
            ],
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='coverletter',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='resume',
        ),
    ]
