# Generated by Django 3.2.1 on 2023-06-05 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='rev_message',
            field=models.TextField(default=2, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='rev_subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=122, unique=True),
            preserve_default=False,
        ),
    ]
