# Generated by Django 3.2.1 on 2023-06-05 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20230605_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='jobseeker',
            field=models.ManyToManyField(limit_choices_to={'role_id': 2}, to=settings.AUTH_USER_MODEL),
        ),
    ]
