# Generated by Django 3.2.1 on 2023-06-06 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_appliedjob_jobseeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='job',
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='jobseeker',
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='jobseeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
