# Generated by Django 3.2.1 on 2023-06-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='role_id',
            field=models.PositiveIntegerField(choices=[(1, 'User'), (2, 'Job Seeker'), (3, 'employer')], default=1),
        ),
    ]
