# Generated by Django 3.2.1 on 2023-06-08 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
